In [131]:
import numpy as np

In [4]:
v1= np.array([1,2,3,4,5])
v2= np.array([6,7,8,9,10])
v1

array([1, 2, 3, 4, 5])

In [20]:
class Student:
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

In [21]:
s1=Student("John", 20)
s1.name

'John'

In [25]:
vec= np.array([1, 2, 3])
mat=vec.reshape(2, 3)
print(mat)

ValueError: cannot reshape array of size 3 into shape (2,3)

In [23]:
vec=np.array([1, 2, 3])
vec.shape[0]

3

In [24]:
vector1 = np.array([1, 2, 3])
mat=vector1.reshape(vec.shape[0], 1)
print(mat)

[[1]
 [2]
 [3]]

In [26]:
def array_reshape(arr,row=-1,col=-1):
    try:
        arr=np.array(arr)
        return arr.reshape(row,col)
    except Exception as e:
       raise ValueError(f"Reshape failed: {e}")

In [27]:
vec=[1, 2, 3, 4, 5, 6]
print("test1(2*3 matrix):",array_reshape(vec,2,3))

test1(2*3 matrix): [[1 2 3]
 [4 5 6]]

In [30]:
class C:
    x=3

In [28]:
mat=np.array([["t",2.5,6],
              [4,5,True]])
fmat=mat.astype(float)
print(fmat)
print(fmat.dtype)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
v=np.array([1,2,3,4,5])
v[1]

np.int64(2)

In [34]:
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [0,0,0]])
m[1:3,0:2]
m[-3:-1,-3:-1]

array([[4, 5],
       [7, 8]])

In [37]:
mat=np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
may_transpose=mat.T
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [38]:
mat=np.zeros((3, 3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
mean_filter=np.empty((3, 3))
mean_filter

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
angles=np.array([0, 30, 45, 60, 90])
angles

array([ 0, 30, 45, 60, 90])

In [50]:
vec=np.linspace(0, 10,num=10)
vec

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [51]:
vec=np.identity(3,dtype="float32")
vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [52]:
import random
np.random.randint((3,3))

array([1, 1], dtype=int32)

In [53]:
import numpy as np

In [54]:
a=np.array([1, 2, 3,4,5,6])
a.shape

(6,)

In [69]:
class Student:
    def __init__(self, name) -> None:
        self._name = name
class student(Student):
    def __init__(self, name) -> None:
        super().__init__(name)

In [63]:
s1=Student("Maha")
s1._name
s1.__dict__

{'_name': 'Maha'}

In [75]:
class Student:
    def __init__(self, name) -> None:
        self.__name = name
    @property    
    def name(self):
        return self.__name  
    @name.setter  
    def name (self, value):
        self.__name = value

In [79]:
s1=Student("John")
s1.name="maha"
s1.name

'maha'

In [80]:
vec=np.linspace(0,10,num=25)
mat=vec.reshape(5,5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [82]:
I=np.identity(3,dtype="float64")
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.random.random((3,3))

array([[0.19172123, 0.39521696, 0.75739375],
       [0.89421708, 0.51180096, 0.76345688],
       [0.59689037, 0.51626744, 0.73887236]])

In [85]:
np.random.randint(0,11,(5,5))

array([[ 7,  5,  5,  8, 10],
       [ 5,  4,  2,  9,  8],
       [ 8,  1,  2, 10,  7],
       [ 6,  6,  8,  6, 10],
       [10,  2,  3,  8,  8]], dtype=int32)

In [86]:
a=['maha','khaled','heba']
np.random.choice(a, size=(3,4))

array([['maha', 'maha', 'heba', 'maha'],
       ['khaled', 'maha', 'khaled', 'maha'],
       ['maha', 'maha', 'khaled', 'heba']], dtype='<U6')

In [92]:
mat1=np.ones((3,4))
mat2=np.zeros((5,3))
np.savez('file_test.npz',ones_mat=mat1, zeros_mat=mat1,zeros_mat=mat2)

SyntaxError: keyword argument repeated: zeros_mat (1458699674.py, line 3)

In [91]:
with np.load('file_test.npz') as file:
    mat1=file['ones_mat']
    mat2=file['zeros_mat']

FileNotFoundError: [Errno 2] No such file or directory: 'file_test.npz'

In [89]:
print(mat1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [90]:
print(mat2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [93]:
m1=np.array([[1, 2, 3],
             [0, 0, 0]])
m2=np.array([[ 5, 6, 7],
             [1,1,1]])
mat3=np.hstack((m1,m2))
mat3

array([[1, 2, 3, 5, 6, 7],
       [0, 0, 0, 1, 1, 1]])

In [95]:
s=4
v=np.array([2,4,3,4,10])
#v==s
v.__eq__(s)
v.__lt__

In [97]:
class Student:
    def __init__(self, name):
        self.name = name
    def __eq__(self, value): 
        pass

In [98]:
s1=Student("maha")
s2=Student("maha")
s1=s2

In [99]:
v=np.array([2,3,4,5,2])
np.any(v>=1)

np.True_

In [100]:
v1=np.array([1,2,3,4,5])
v2=np.array([2,3,0,5,3])
np.isclose(v1,v2,atol=1)

array([ True,  True, False,  True, False])

In [ ]:
def is_close(v1,v2)->bool:

In [ ]:
pip ins

In [ ]:
from scipy.sparse import csr_matrix,csc_matrix
mat=np.array([])

In [101]:
import pandas as pd

In [105]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [108]:
data = [[1, 444, 'abc'],
    [2, 555, 'def'],
    [3, 666, 'ghi'],
    [4, 444, 'xyz']]
df = pd.DataFrame(data, columns=["idx", "std_id", "depart"])
df

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [109]:
display(df)
colum= ["idx-1",'std_id','dep']
df.index=Index

   idx  std_id depart
0    1     444    abc
1    2     555    def
2    3     666    ghi
3    4     444    xyz

In [110]:
df.dtypes

idx       int64
std_id    int64
depart      str
dtype: object

In [112]:
df[].dtypes

SyntaxError: invalid syntax (994392277.py, line 1)

In [116]:
cols= ['idx-1','dep']
df.rename(columns={'idx': 'idx-1', 'depart': 'dep'}, inplace=True)
df[cols] = df[cols].astype('category')

In [117]:
df.dtypes

idx-1     category
std_id       int64
dep       category
dtype: object

In [118]:
df.tail(2)

  idx-1  std_id  dep
2     3     666  ghi
3     4     444  xyz

In [120]:
df.describe(include="category")

        idx-1  dep
count       4    4
unique      4    4
top         1  abc
freq        1    1

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   idx-1   4 non-null      category
 1   std_id  4 non-null      int64
 2   dep     4 non-null      category
dtypes: category(2), int64(1)
memory usage: 408.0 bytes

In [125]:
d=df['dapart'].value_counts()
d

KeyError: 'dapart'

In [126]:
df['std_id'].sum()

np.int64(2109)

In [127]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [128]:
x=df.values
type(x)

numpy.ndarray

In [130]:
df.replace(555,"maha")
df

  idx-1  std_id  dep
0     1     444  abc
1     2     555  def
2     3     666  ghi
3     4     444  xyz