In [1]:
import pandas as pd

df = pd.read_csv("Titanic.csv")

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [11]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)

In [8]:
df.head

<bound method NDFrame.head of      Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]>

In [9]:
Drop_COLUMS=["PassengerId", "Name", "Ticket"]

In [12]:
def drop_cols(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    return df.drop(columns=cols)

df = drop_cols(df,Drop_COLUMS)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [13]:
#check data type

In [15]:
class Student:
    def __init__(self, name) -> None:
        self._name = name

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, value):
        self._name = value

In [16]:
df.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [21]:
dtypes = df.dtypes
n_uniq = df.nunique()
n_uniq
dtypes = df.dtypes
n_uniq = df.nunique()
n_uniq
pd.DataFrame({"Dtypes": dtypes, "Num_unique": n_uniq})

           Dtypes  Num_unique
Survived    int64           2
Pclass      int64           3
Sex           str           2
Age       float64          88
SibSp       int64           7
Parch       int64           7
Fare      float64         248
Cabin         str         147
Embarked      str           3

In [23]:
null = df.isnull().sum()
null
null

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [28]:
cols=['pclass','survived','sibsp','sex','parch','Embarked']
cols = ['Pclass', 'Survived', 'SibSp', 'Sex', 'Parch', 'Embarked']
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [27]:
df.shape[0]

891

In [29]:
null=df.isnull().sum()
ratio=null/df.shape[0]
null

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [30]:
df=df.dropna(subset=['Embarked'])

In [31]:
df=df.drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [ ]:
mean = df["Age"].mean()
mean

In [32]:
df.describe()

              Age        Fare
count  712.000000  889.000000
mean    29.642093   32.096681
std     14.492933   49.697504
min      0.420000    0.000000
25%     20.000000    7.895800
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [33]:
num_cols=df.select_dtypes("number").columns
num_cols

Index(['Age', 'Fare'], dtype='str')